DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users(
  user_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  fname VARCHAR (100) NOT NULL ,
  lname VARCHAR (100) NOT NULL ,
  email VARCHAR (100) NOT NULL UNIQUE,
  telephone VARCHAR (50) NOT NULl,
  password VARCHAR (100) NOT NULL,
  gender VARCHAR (10) NOT NULL,
  street_address VARCHAR (100) NOT NULL,
  work_sch_address VARCHAR (100) NOT NULL,
  city VARCHAR (100) NOT NULL,
  country VARCHAR (100) NOT NULL,
  state VARCHAR (100) NOT NULL,
  local_govt VARCHAR (100) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS contact_us;
CREATE TABLE IF NOT EXISTS contact_us(
  contact_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  fullname VARCHAR (100) NOT NULL ,
  email VARCHAR (100) NOT NULL UNIQUE,
  phone VARCHAR (50) NOT NULl,
  subject VARCHAR (100) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);