DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users(
  user_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  fname VARCHAR (100) NOT NULL ,
  lname VARCHAR (100) NOT NULL ,
  email VARCHAR (100) NOT NULL UNIQUE,
  telephone VARCHAR (50) NOT NULl,
  password VARCHAR (100) NOT NULL,
  gender VARCHAR (10) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS ordering_details;
CREATE TABLE IF NOT EXISTS ordering_details(
  ordering_details_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  user_id INT UNSIGNED ,
  address_used INT UNSIGNED DEFAULT 0,
  fname VARCHAR (100) NOT NULL ,
  lname VARCHAR (100) NOT NULL ,
  email VARCHAR (100) NOT NULL ,
  phone VARCHAR (50) NOT NULl,
  str_address VARCHAR (100) NOT NULL,
  wrk_address VARCHAR (100) NOT NULL,
  city VARCHAR (100) NOT NULL,
  country VARCHAR (100) NOT NULL,
  state VARCHAR (100) NOT NULL,
  lga VARCHAR (100) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ordering_details_user_id FOREIGN KEY (user_id) REFERENCES users(user_id)
);

DROP TABLE IF EXISTS shoe;
CREATE TABLE IF NOT EXISTS shoe(
  shoe_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  shoe_desc VARCHAR (200) NOT NULL ,
  shoe_type VARCHAR (25) NOT NULL,
  picture VARCHAR (100) NOT NULl,
  shoe_price VARCHAR (200) NOT NULL,
  available_no INT(100) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS orders;
CREATE TABLE IF NOT EXISTS orders(
  order_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id INT UNSIGNED,
  shoe_id INT UNSIGNED ,
  ordering_details_id INT UNSIGNED,
  quantity_ordered INT UNSIGNED NOT NULL ,
  order_status VARCHAR (200) NOT NULL ,
  order_ref_no VARCHAR (200) NOT NULL,
  remove INT UNSIGNED DEFAULT 0,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP ,
  CONSTRAINT fk_orders_user_id FOREIGN KEY (user_id) REFERENCES users(user_id) ,
  CONSTRAINT fk_orders_shoe_id FOREIGN KEY (shoe_id) REFERENCES shoe(shoe_id)
);

DROP TABLE IF EXISTS contact_us;
CREATE TABLE IF NOT EXISTS contact_us(
  contact_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  fullname VARCHAR (100) NOT NULL ,
  email VARCHAR (100) NOT NULL,
  phone VARCHAR (50) NOT NULl,
  subject VARCHAR (100) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS blog;
CREATE TABLE IF NOT EXISTS blog(
  blog_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  blog_news_title VARCHAR (100) NOT NULL,
  blog_news VARCHAR (1000) NOT NULL ,
  picture VARCHAR (200) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS admin;
CREATE TABLE IF NOT EXISTS admin(
  admin_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  admin_username VARCHAR (100) NOT NULL UNIQUE ,
  admin_password VARCHAR (100) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);